CREATE SEQUENCE KAFKA_PRODUCER_RECORD_ID_SEQ;

CREATE TABLE KAFKA_PRODUCER_RECORD (
    ID                      BIGINT NOT NULL PRIMARY KEY,
    TOPIC                   VARCHAR(100) NOT NULL,
    KEY                     BYTEA NOT NULL,
    VALUE                   BYTEA NOT NULL,
    CREATED_AT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE SEQUENCE KAFKA_CONSUMER_RECORD_ID_SEQ;

CREATE TABLE KAFKA_CONSUMER_RECORD (
    ID                      BIGINT NOT NULL PRIMARY KEY,
    TOPIC                   VARCHAR(100) NOT NULL,
    PARTITION               INTEGER NOT NULL,
    RECORD_OFFSET           BIGINT NOT NULL,
    KEY                     BYTEA NOT NULL,
    VALUE                   BYTEA NOT NULL,
    CREATED_AT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (TOPIC, PARTITION, RECORD_OFFSET)
);
