CREATE SEQUENCE KAFKA_CONSUMER_RECORD_ID_SEQ;

CREATE TABLE KAFKA_CONSUMER_RECORD (
    ID                      NUMBER(18) NOT NULL PRIMARY KEY,
    TOPIC                   VARCHAR(100) NOT NULL,
    PARTITION               NUMBER(9) NOT NULL,
    RECORD_OFFSET           NUMBER(18) NOT NULL,
    RETRIES                 NUMBER(9) DEFAULT 0 NOT NULL,
    LAST_RETRY              TIMESTAMP,
    KEY                     BLOB,
    VALUE                   BLOB,
    HEADERS_JSON            CLOB,
    RECORD_TIMESTAMP        NUMBER(18),
    CREATED_AT              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (TOPIC, PARTITION, RECORD_OFFSET)
);

CREATE INDEX KAFKA_CONSUMER_RECORD_TOPIC_PARTITION_IDX ON KAFKA_CONSUMER_RECORD (TOPIC, PARTITION);

